<?php

namespace Database\Seeders;

use App\Models\Location;
use App\Models\Organization;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function () {
            $this->seedLocations();
        });
    }

    private function seedLocations(): void
    {
        $enteDeturismo = Organization::where('slug', 'ente-turismo-tucuman')->first();

        $locations = [
            // Centros de eventos y convenciones
            [
                'name' => 'Centro de Convenciones Tucumán',
                'address' => 'Av. Soldati 330',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8083,
                'longitude' => -65.2176,
                'description' => 'Moderno centro de convenciones con capacidad para grandes eventos',
                'phone' => '+54 381 4300000',
                'email' => 'info@centroconvenciones.tuc.gov.ar',
                'additional_info' => [
                    'capacity' => 2000,
                    'parking_spaces' => 500,
                    'has_wifi' => true,
                    'has_audio_system' => true,
                    'accessibility' => true,
                ],
            ],

            // Centros culturales y teatros
            [
                'name' => 'Teatro San Martín',
                'address' => 'San Martín 251',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8287,
                'longitude' => -65.2049,
                'description' => 'Principal teatro de la provincia, sede de importantes eventos culturales',
                'phone' => '+54 381 4221752',
                'email' => 'teatrosanmartin@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 800,
                    'has_parking' => false,
                    'has_audio_system' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Casa Histórica de la Independencia',
                'address' => 'Congreso 151',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8319,
                'longitude' => -65.2050,
                'description' => 'Sitio histórico donde se declaró la Independencia Argentina en 1816',
                'phone' => '+54 381 4310826',
                'email' => 'casahistorica@cultura.gob.ar',
                'additional_info' => [
                    'capacity' => 200,
                    'has_parking' => false,
                    'historic_monument' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Casa de Gobierno de Tucumán',
                'address' => '25 de Mayo 90',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8286,
                'longitude' => -65.2044,
                'description' => 'Sede del poder ejecutivo provincial, edificio histórico con salones para eventos oficiales',
                'phone' => '+54 381 4840000',
                'email' => 'protocolo@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 300,
                    'has_parking' => true,
                    'official_use' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Teatro Mercedes Sosa',
                'address' => 'San Martín 1100',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8254,
                'longitude' => -65.1989,
                'description' => 'Teatro moderno dedicado a la artista tucumana, con excelente acústica',
                'phone' => '+54 381 4524575',
                'email' => 'teatromercedessosa@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 600,
                    'has_parking' => true,
                    'has_audio_system' => true,
                    'accessibility' => true,
                ],
            ],

            // Plazas y espacios públicos
            [
                'name' => 'Parque 9 de Julio',
                'address' => 'Av. Aconquija s/n',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8167,
                'longitude' => -65.2167,
                'description' => 'Amplio parque urbano ideal para eventos al aire libre y festivales',
                'phone' => '+54 381 4300001',
                'email' => 'eventos@parque9julio.tuc.gov.ar',
                'additional_info' => [
                    'capacity' => 10000,
                    'outdoor_space' => true,
                    'has_stage' => true,
                    'has_restrooms' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Plaza Independencia',
                'address' => '25 de Mayo y San Martín',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8289,
                'longitude' => -65.2046,
                'description' => 'Plaza principal de la ciudad, centro cívico y punto de encuentro tradicional',
                'phone' => '+54 381 4300002',
                'email' => 'plazas@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 5000,
                    'outdoor_space' => true,
                    'has_monument' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Plaza Urquiza',
                'address' => 'Av. Sarmiento y Muñecas',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8344,
                'longitude' => -65.2097,
                'description' => 'Tradicional plaza del barrio sur con amplio espacio para eventos comunitarios',
                'phone' => '+54 381 4300003',
                'email' => 'plazas@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 3000,
                    'outdoor_space' => true,
                    'has_lighting' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Paseo de la Independencia',
                'address' => 'Pasaje Zelaya',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8295,
                'longitude' => -65.2053,
                'description' => 'Paseo peatonal histórico con galerías comerciales y espacios para muestras',
                'phone' => '+54 381 4300004',
                'email' => 'paseoindependencia@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 1000,
                    'outdoor_space' => true,
                    'commercial_area' => true,
                    'accessibility' => true,
                ],
            ],

            // Hoteles y centros de eventos
            [
                'name' => 'Hotel Catalinas Park',
                'address' => 'Av. Soldati 380',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8076,
                'longitude' => -65.2181,
                'description' => 'Hotel 5 estrellas con amplios salones para convenciones y eventos corporativos',
                'phone' => '+54 381 4500000',
                'email' => 'eventos@catalinaspark.com.ar',
                'additional_info' => [
                    'capacity' => 1000,
                    'has_parking' => true,
                    'has_accommodation' => true,
                    'has_catering' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Sheraton Tucumán Hotel',
                'address' => 'Av. Soldati 440',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8068,
                'longitude' => -65.2188,
                'description' => 'Hotel internacional con instalaciones de primer nivel para eventos empresariales',
                'phone' => '+54 381 4508000',
                'email' => 'eventos@sheratontucuman.com',
                'additional_info' => [
                    'capacity' => 800,
                    'has_parking' => true,
                    'has_accommodation' => true,
                    'has_catering' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Hotel Garden Park',
                'address' => 'Av. Aconquija 2100',
                'city' => 'Yerba Buena',
                'postal_code' => '4107',
                'latitude' => -26.8144,
                'longitude' => -65.2833,
                'description' => 'Hotel boutique con jardines y salones para eventos sociales y corporativos',
                'phone' => '+54 381 4253000',
                'email' => 'eventos@gardenpark.com.ar',
                'additional_info' => [
                    'capacity' => 400,
                    'has_parking' => true,
                    'has_accommodation' => true,
                    'outdoor_space' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Swiss Hotel Metropol',
                'address' => '24 de Septiembre 524',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8312,
                'longitude' => -65.2028,
                'description' => 'Hotel céntrico con salón de eventos y fácil acceso desde cualquier punto de la ciudad',
                'phone' => '+54 381 4311180',
                'email' => 'eventos@swissmetropol.com.ar',
                'additional_info' => [
                    'capacity' => 250,
                    'has_parking' => false,
                    'has_accommodation' => true,
                    'central_location' => true,
                    'accessibility' => true,
                ],
            ],

            // Museos
            [
                'name' => 'Museo Casa Padilla',
                'address' => '25 de Mayo 36',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8278,
                'longitude' => -65.2052,
                'description' => 'Museo histórico en casona colonial con colección de arte y objetos de época',
                'phone' => '+54 381 4310761',
                'email' => 'casapadilla@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 100,
                    'has_parking' => false,
                    'historic_building' => true,
                    'accessibility' => false,
                ],
            ],
            [
                'name' => 'Museo Folklórico Provincial',
                'address' => '24 de Septiembre 565',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8316,
                'longitude' => -65.2024,
                'description' => 'Museo dedicado a las tradiciones y cultura popular tucumana',
                'phone' => '+54 381 4211250',
                'email' => 'museofolklorico@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 150,
                    'has_parking' => false,
                    'cultural_events' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Museo Provincial de Bellas Artes Timoteo Navarro',
                'address' => '9 de Julio 44',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8275,
                'longitude' => -65.2065,
                'description' => 'Principal museo de arte de la provincia con exposiciones permanentes y temporales',
                'phone' => '+54 381 4221727',
                'email' => 'museobellasartes@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 200,
                    'has_parking' => false,
                    'art_exhibitions' => true,
                    'accessibility' => true,
                ],
            ],

            // Lugares turísticos serranos
            [
                'name' => 'Complejo Turístico Tafí del Valle',
                'address' => 'Ruta Provincial 307 Km 5',
                'city' => 'Tafí del Valle',
                'postal_code' => '4137',
                'latitude' => -26.8556,
                'longitude' => -65.7086,
                'description' => 'Complejo turístico en las montañas, perfecto para eventos de turismo rural',
                'phone' => '+54 3867 421000',
                'email' => 'eventos@tafiturismo.tuc.gov.ar',
                'additional_info' => [
                    'capacity' => 300,
                    'mountain_location' => true,
                    'has_accommodation' => true,
                    'outdoor_activities' => true,
                    'accessibility' => false,
                ],
            ],
            [
                'name' => 'Cristo Redentor - Cerro San Javier',
                'address' => 'Cumbre Cerro San Javier',
                'city' => 'Yerba Buena',
                'postal_code' => '4107',
                'latitude' => -26.7793,
                'longitude' => -65.3433,
                'description' => 'Mirador panorámico con monumento al Cristo, ideal para eventos especiales',
                'phone' => '+54 381 4250100',
                'email' => 'sanjavier@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 500,
                    'mountain_location' => true,
                    'outdoor_space' => true,
                    'panoramic_view' => true,
                    'accessibility' => false,
                ],
            ],
            [
                'name' => 'Dique El Cadillal',
                'address' => 'Ruta Provincial 315 Km 25',
                'city' => 'El Cadillal',
                'postal_code' => '4111',
                'latitude' => -26.6167,
                'longitude' => -65.2167,
                'description' => 'Embalse con área recreativa ideal para eventos deportivos y náuticos',
                'phone' => '+54 381 4900100',
                'email' => 'elcadillal@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 2000,
                    'water_activities' => true,
                    'outdoor_space' => true,
                    'has_camping' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Villa Nougués',
                'address' => 'Camino a Villa Nougués Km 15',
                'city' => 'Villa Nougués',
                'postal_code' => '4107',
                'latitude' => -26.8500,
                'longitude' => -65.3333,
                'description' => 'Villa serrana histórica con arquitectura inglesa y clima fresco todo el año',
                'phone' => '+54 381 4251000',
                'email' => 'villanougues@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 200,
                    'mountain_location' => true,
                    'historic_site' => true,
                    'outdoor_space' => true,
                    'accessibility' => false,
                ],
            ],
            [
                'name' => 'Ruinas de Quilmes',
                'address' => 'Ruta Provincial 357 Km 10',
                'city' => 'Quilmes',
                'postal_code' => '4141',
                'latitude' => -26.4667,
                'longitude' => -66.0500,
                'description' => 'Sitio arqueológico precolombino con museo y centro de interpretación',
                'phone' => '+54 3892 421075',
                'email' => 'ruinasdequilmes@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 500,
                    'archaeological_site' => true,
                    'has_museum' => true,
                    'outdoor_space' => true,
                    'accessibility' => false,
                ],
            ],
            [
                'name' => 'Amaicha del Valle',
                'address' => 'Plaza Central s/n',
                'city' => 'Amaicha del Valle',
                'postal_code' => '4137',
                'latitude' => -26.6167,
                'longitude' => -65.9167,
                'description' => 'Pueblo calchaquí sede de la Fiesta Nacional de la Pachamama',
                'phone' => '+54 3892 421100',
                'email' => 'turismo@amaichadelvalle.gob.ar',
                'additional_info' => [
                    'capacity' => 3000,
                    'outdoor_space' => true,
                    'cultural_events' => true,
                    'indigenous_heritage' => true,
                    'accessibility' => true,
                ],
            ],

            // Espacios deportivos
            [
                'name' => 'Estadio José Fierro',
                'address' => 'Av. Leandro N. Alem 500',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8372,
                'longitude' => -65.1950,
                'description' => 'Estadio del Club Atlético Tucumán, sede de eventos deportivos y recitales',
                'phone' => '+54 381 4244000',
                'email' => 'estadio@catucuman.com.ar',
                'additional_info' => [
                    'capacity' => 35000,
                    'has_parking' => true,
                    'sports_venue' => true,
                    'concert_venue' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Estadio Monumental José María Moreno',
                'address' => 'Av. Mate de Luna 2100',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8114,
                'longitude' => -65.1858,
                'description' => 'Estadio de Atlético Tucumán para grandes eventos deportivos y espectáculos',
                'phone' => '+54 381 4241000',
                'email' => 'estadiomonumental@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 30000,
                    'has_parking' => true,
                    'sports_venue' => true,
                    'concert_venue' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Polideportivo Delmi',
                'address' => 'Av. Perón 2500',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8456,
                'longitude' => -65.2333,
                'description' => 'Complejo deportivo con canchas, piscinas y gimnasio para eventos multideportivos',
                'phone' => '+54 381 4350000',
                'email' => 'polideportivodelmi@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 5000,
                    'has_parking' => true,
                    'indoor_courts' => true,
                    'swimming_pool' => true,
                    'accessibility' => true,
                ],
            ],

            // Bodegas y quintas
            [
                'name' => 'Quinta Agronómica',
                'address' => 'Av. Roca 1900',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8233,
                'longitude' => -65.1917,
                'description' => 'Histórica quinta con jardines botánicos y espacios para eventos al aire libre',
                'phone' => '+54 381 4364000',
                'email' => 'quintaagronomica@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 800,
                    'outdoor_space' => true,
                    'botanical_garden' => true,
                    'historic_site' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Finca Santa Rosa',
                'address' => 'Ruta Provincial 340 Km 8',
                'city' => 'Famaillá',
                'postal_code' => '4132',
                'latitude' => -27.0500,
                'longitude' => -65.4000,
                'description' => 'Finca productiva con viñedos y cava, ideal para eventos enoturísticos',
                'phone' => '+54 381 4900200',
                'email' => 'fincasantarosa@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 200,
                    'has_parking' => true,
                    'wine_tasting' => true,
                    'outdoor_space' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Bodega La Banda',
                'address' => 'Ruta Nacional 38 Km 780',
                'city' => 'Colalao del Valle',
                'postal_code' => '4141',
                'latitude' => -26.3667,
                'longitude' => -66.0333,
                'description' => 'Bodega artesanal en los Valles Calchaquíes con degustaciones y eventos',
                'phone' => '+54 3892 490100',
                'email' => 'bodegalabanda@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 150,
                    'has_parking' => true,
                    'wine_tasting' => true,
                    'mountain_location' => true,
                    'accessibility' => false,
                ],
            ],

            // Universidades y centros educativos
            [
                'name' => 'Centro Cultural Virla - UNT',
                'address' => '25 de Mayo 265',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8298,
                'longitude' => -65.2038,
                'description' => 'Centro cultural universitario con auditorio y salas de exposición',
                'phone' => '+54 381 4247752',
                'email' => 'centrovirla@unt.edu.ar',
                'additional_info' => [
                    'capacity' => 400,
                    'has_parking' => false,
                    'has_audio_system' => true,
                    'cultural_events' => true,
                    'accessibility' => true,
                ],
            ],
            [
                'name' => 'Anfiteatro del Parque Avellaneda',
                'address' => 'Av. Mate de Luna 3000',
                'city' => 'San Miguel de Tucumán',
                'postal_code' => '4000',
                'latitude' => -26.8050,
                'longitude' => -65.1800,
                'description' => 'Anfiteatro al aire libre rodeado de naturaleza, ideal para espectáculos y festivales',
                'phone' => '+54 381 4350100',
                'email' => 'parqueavellaneda@tucuman.gob.ar',
                'additional_info' => [
                    'capacity' => 4000,
                    'outdoor_space' => true,
                    'has_stage' => true,
                    'has_parking' => true,
                    'accessibility' => true,
                ],
            ],
        ];

        foreach ($locations as $locationData) {
            Location::create(array_merge($locationData, [
                'state' => 'Tucumán',
                'country' => 'Argentina',
                'is_active' => true,
                'entity_id' => $enteDeturismo->id,
            ]));
        }

        $this->command->info('Locations created successfully!');
        $this->command->info('- 30 locations created for Ente de Turismo');
    }
}
